DB-1321
syngenta-digital/package-python-dta pull request #107
Opened 2022-04-07 00:30 UTC by macedomario

related to - https://github.com/syngenta-digital/package-python-databus-shared/pull/85

2022-04-07 14:50 UTC, paulcruse-syn requested changes
What are we trying to accomplish with this PR?

Can we setup a meeting to discuss if necessary?

2022-04-08 14:39 UTC, paulcruse-syn requested changes
Great work!

Just some small changes and we are good.

2022-04-08 14:39 UTC, paulcruse-syn commented on syngenta_digital_dta/file_system/adapter.py
> +            return self.__download_file(**kwargs)
There should be a difference between `http_link` and `s3_link`, s3_link should be `s3_path` and would require use of the S3 adapter to pull that object down.

2022-04-08 17:53 UTC, macedomario commented on syngenta_digital_dta/file_system/adapter.py
> +        publish = kwargs.get('publish', True)
I think the assignment for `destination_path` makes sense since we are using that multiple times in the method. I will update `publish` though.

2022-04-11 15:55 UTC, paulcruse-syn approved these changes

2022-04-18 14:51 UTC, merged